### ISSUE TITLE
В проверочном коде в задании "Изменяемые и неизменяемые типы данных в Python" в слове "апельсин" буква "a" написана на латинице.

### ISSUE THREAD

**Issue by esaukova** [hse-labs/DSH-PY101-issues#2]
# Описание
При запуске проверки кода в задании "Изменяемые и неизменяемые типы данных в Python", программа выдаёт ответ, что задание выполнено неправильно, хотя визуально ошибки нет

# Локация дефекта

Процедурное программирование на языку Python - Базовые типы языка Python и работа с ними - Составные типы данных - Изменяемые и неизменяемые типы данных в Python

# Шаги воспроизведения

1. Выполнить задание по теме "Изменяемые и неизменяемые типы данных в Python"
2. Нажать Check
3. Посмотреть на вывод результата проверки

*Ожидаемый результат:* Консоль выдает сообщение об успешном выполнение задания: "Correct"

*Фактический результат:* Консоль выдает сообщение об ошибке выполнения задания: "Incorrect"                                     
 Expected: ['яблоко', 'банан', 'апельсин', 'виноград'] Actual: ['яблоко', 'банан', 'апельсин', 'виноград']

# Скриншот
![Изменяемые типы данных](https://github.com/hse-labs/DSH-PY101-issues/assets/81514189/aae4c032-ebd7-4c1d-bcb8-1e701c2819af)

![Изменяемые типы данных_2](https://github.com/hse-labs/DSH-PY101-issues/assets/81514189/827a9ee5-ca72-4a99-a8a8-722862311b43)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** PyCharm 2023.1.3 (Community Edition)
*  **Python:** Python 3.10.11

**Comment by aeksei** [comment]
@esaukova  Добрый день! Спасибо большое за подробную обратную связь.  
Этот момент исправлен и задание курса обновлено.  
Чтобы обновить курс в среде разработки нужно нажать на значок "S" в правом нижнем углу. 
<img width="201" alt="image" src="https://github.com/hse-labs/DSH-PY101-issues/assets/14962819/ca59f7cb-c05a-46cd-9cf1-ae0c2bb23561">
Так как задание было выполнено, в web версии может показывать, что задание обновлено авторами, но прогресс должен сохраниться
