### ISSUE TITLE
Ошибка в описании задачи "Продолжение финансового планирования"

### ISSUE THREAD

**Issue by esaukova** [hse-labs/DSH-PY101-issues#4]
# Описание
В описание задачи лабораторной работы "Продолжение финансового планирования" указано некорректное значение увеличения расходов на 5%, а в задачи используется 3% (корректное значение)

# Локация дефекта

Процедурное программирование на языку Python - Условия и циклы - Лабораторные работы - Продолжение финансового планирования

# Шаги воспроизведения

1. Открыть задание лабораторной работы "Продолжение финансового планирования"
2. Прочитать задание, обратив внимание, что в описание указано 5%, а в файле main.py указано 3% в форме десятичной дроби 
3. Исправить 3% на 5% (как в условии)
4. Выполнить задание
5. Нажать кнопку Check
6. Посмотреть на вывод результата проверки

*Ожидаемый результат:* Консоль выдает сообщение об успешном выполнение задания: "Correct"

*Фактический результат:* Консоль выдает сообщение об ошибке выполнения задания: "Incorrect"                                     
 Expected: Подушка безопасности, чтобы протянуть 10 месяцев без долгов: 18783     (__используется 3%__)
 Actual: Подушка безопасности, чтобы протянуть 10 месяцев без долгов: 25467          (__используется 5%__)

# Скриншот
![Описание_некоректное](https://github.com/hse-labs/DSH-PY101-issues/assets/81514189/5879a2c7-4146-4274-9c4f-f5b47d6afe14)

![Задача](https://github.com/hse-labs/DSH-PY101-issues/assets/81514189/0415f6a4-b1a2-405d-9246-d5ac5457b514)

# Окружение 
* **Операционная система:** Windows 10 Home Single Language
*  **IDE:** PyCharm 2023.1.3 (Community Edition)
*  **Python:** Python 3.10.11

**Comment by aeksei** [comment]
Поправил описание. Обновил курс на Stepik. 
Нужно обновить курс в IDE, чтобы получить актуальную версию описания. 

Ожидаемый ответ с учетом 3%
