### ISSUE TITLE
Не срабатывает тестирование в задании 4.5.4  Практическое задание: Список имен учеников

### ISSUE THREAD

**Issue by vadimnktn** [hse-labs/DSH-PY101-issues#6]
Именно это задание не хочет проверяться в IDEA - синхронизация есть, левое и правое задание ОК, а именно это он не тестирует.
Пишет справа внизу "Failed to launch cheсking"

После того как убрал из кода строку 
if __name__ == '__main__':
и пустую строку над ней тестирование прошло успешно.

**Comment by aeksei** [comment]
#13
